spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    showSql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  datasource:
    platform: h2
    url: jdbc:h2:mem:seoulphone;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    initialization-mode: EMBEDDED

    hikari:
      maximum-pool-size: 200
      connection-timeout: 2000
      connection-test-query: SELECT 1
      validation-timeout: 5000

  data:
    web:
      pageable:
        page-parameter: pageNo
        size-parameter: numOfRows
        default-page-size: 10
        one-indexed-parameters: true

# feign
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic

ribbon:
  eureka:
    enabled: false

opendata-client:
  key: '{cipher}afcc239817768348a6b2a453e780644781a4de3a662aaee7225aee9c6017f0cbc100117a2885bedc5d5a412746cf1acaf9d9d7a103924d7e3ed8270b74a44c7c84f134d38be790f516cc9617a3f78664f2d81c0598effc3fdee67314ad46872563742d6a23982abb69378dab763ad225d449839fde602283693850fe71022293'
  ribbon:
    IsSecure: true
    MaxAutoRetries: 5